apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # do not use base
  # - ../../../base/helm
  
  # instead, directly reference the helm chart, so we can have different values per environment
  - helmChart.yaml
