apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../apps/envs/rebuild

components:
  - ../../../../../_components/rebuild

patches:
  - path: root.yaml
