apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../apps/envs/poc

components:
  - ../../../../../_components/poc

generators:
  - ./helm

patches:
  - path: root.yaml
