apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: &repo https://github.com/isejalabs/homelab.git
        revision: HEAD
        directories:
          - path: k8s/core/*/*/base
  template:
    metadata:
      name: "core-{{index .path.segments 3}}"
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: core
      revisionHistoryLimit: 3
      source:
        repoURL: *repo
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 3}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - Replace=false
          - IgnoreMissingTemplate=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      info:
        - name: "Description"
          value: "Application: {{index .path.segments 3}}"
