apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - http-route.yaml

helmCharts:
  - name: checkmk
    repo: https://checkmk.github.io/checkmk_kube_agent
    version: 1.7.0
    releaseName: checkmk-kube-agent
    namespace: checkmk-agent
    valuesFile: values.yaml
