apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../apps/envs/prod

components:
  - ../../../../../_components/prod

generators:
  - ./helm

patches:
  - path: root.yaml
