apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: appset-apps.yaml
  - path: appset-core.yaml
  - path: appset-infra.yaml
  # - path: patch-revision.yaml
  #   target:
  #     kind: ApplicationSet
  #     name: apps
  # - path: patch-revision.yaml
  #   target:
  #     kind: ApplicationSet
  #     name: core
  # - path: patch-revision.yaml
  #   target:
  #     kind: ApplicationSet
  #     name: infra
