apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: checkmk
version: 1.6.0
valuesInline:
  image:
    # Overrides the image tag whose default is the chart appVersion.
    # ref: https://hub.docker.com/r/checkmk/kubernetes-collector/tags
    tag: "1.5.0"
