apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: diag

resources:
  - ns.yaml
  - svc.yaml
  - deployment.yaml

configMapGenerator:
  - name: ssh-install-packages-script
    files:
      - assets/custom-cont-init.d/install-packages.sh