apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-data
  namespace: diag
spec:
  storageClassName: proxmox-csi
  volumeName: pv-test
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
